---
ID: "1fb1d185-7270-4078-a8d1-280205f10d8d"
Parent: "af2bfaa2-b68b-48d4-ae84-85bbba262675"
Template: "af2bfaa2-b68b-48d4-ae84-85bbba262675"
Path: /sitecore/templates/Project/Spark Book Shop/Rendering Parameters/Slider Rendering Parameters/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200811T074342Z
