---
ID: "1b7adb81-1600-4300-ad51-55d87dd6f5f3"
Parent: "b2601a1a-672d-4bc0-9a98-aa5b1c17c45e"
Template: "b2601a1a-672d-4bc0-9a98-aa5b1c17c45e"
Path: /sitecore/templates/Project/Spark Book Shop/Page Types/Home/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190511T053537Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
