---
ID: "c74acc78-17b6-4e62-8c87-94ebb9ba9b81"
Parent: "de4e424a-cb00-44cd-865c-fcb2168c5471"
Template: "de4e424a-cb00-44cd-865c-fcb2168c5471"
Path: /sitecore/templates/Project/Spark Book Shop/Page Types/Article Template/__Standard Values
DB: master
SharedFields:
- ID: "9862ecb6-3e36-452d-8a0f-19272462e727"
  Hint: Published Date
  Value: 20200728T120000Z
Languages:
- Language: en
  Fields:
  - ID: "24d7a5d2-d2b3-4d52-927e-c6722f6587f4"
    Hint: Title
    Value: Article Base level Value
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200724T064547Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
